include $(srctree)/drivers/misc/mediatek/Makefile.custom

ccflags-y += -I./inc
ccflags-y += -I$(MTK_CUSTOM_PATH)/mach/mt6580/pixi3_55/tuner/fc8180/inc/


obj-y += bbm.o fc8180.o fc8180_bb.o fc8180_i2c.o fc8180_isr.o fc8180_ppi.o fc8180_spi.o fc8180_spib.o fc8180_tun.o fci_bypass.o fci_hal.o fci_hpi.o fci_i2c.o fci_oal.o fci_ringbuffer.o fci_tun.o

